//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CarsDatabase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HireEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HireEntities object using the connection string found in the 'HireEntities' section of the application configuration file.
        /// </summary>
        public HireEntities() : base("name=HireEntities", "HireEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HireEntities object.
        /// </summary>
        public HireEntities(string connectionString) : base(connectionString, "HireEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HireEntities object.
        /// </summary>
        public HireEntities(EntityConnection connection) : base(connection, "HireEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCar> tblCars
        {
            get
            {
                if ((_tblCars == null))
                {
                    _tblCars = base.CreateObjectSet<tblCar>("tblCars");
                }
                return _tblCars;
            }
        }
        private ObjectSet<tblCar> _tblCars;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCars(tblCar tblCar)
        {
            base.AddObject("tblCars", tblCar);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HireModel", Name="tblCar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCar object.
        /// </summary>
        /// <param name="vehicleRegNo">Initial value of the VehicleRegNo property.</param>
        public static tblCar CreatetblCar(global::System.String vehicleRegNo)
        {
            tblCar tblCar = new tblCar();
            tblCar.VehicleRegNo = vehicleRegNo;
            return tblCar;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VehicleRegNo
        {
            get
            {
                return _VehicleRegNo;
            }
            set
            {
                if (_VehicleRegNo != value)
                {
                    OnVehicleRegNoChanging(value);
                    ReportPropertyChanging("VehicleRegNo");
                    _VehicleRegNo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("VehicleRegNo");
                    OnVehicleRegNoChanged();
                }
            }
        }
        private global::System.String _VehicleRegNo;
        partial void OnVehicleRegNoChanging(global::System.String value);
        partial void OnVehicleRegNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Make
        {
            get
            {
                return _Make;
            }
            set
            {
                OnMakeChanging(value);
                ReportPropertyChanging("Make");
                _Make = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Make");
                OnMakeChanged();
            }
        }
        private global::System.String _Make;
        partial void OnMakeChanging(global::System.String value);
        partial void OnMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EngineSize
        {
            get
            {
                return _EngineSize;
            }
            set
            {
                OnEngineSizeChanging(value);
                ReportPropertyChanging("EngineSize");
                _EngineSize = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EngineSize");
                OnEngineSizeChanged();
            }
        }
        private global::System.String _EngineSize;
        partial void OnEngineSizeChanging(global::System.String value);
        partial void OnEngineSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateRegistered
        {
            get
            {
                return _DateRegistered;
            }
            set
            {
                OnDateRegisteredChanging(value);
                ReportPropertyChanging("DateRegistered");
                _DateRegistered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateRegistered");
                OnDateRegisteredChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateRegistered;
        partial void OnDateRegisteredChanging(Nullable<global::System.DateTime> value);
        partial void OnDateRegisteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RentalPerDay
        {
            get
            {
                return _RentalPerDay;
            }
            set
            {
                OnRentalPerDayChanging(value);
                ReportPropertyChanging("RentalPerDay");
                _RentalPerDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RentalPerDay");
                OnRentalPerDayChanged();
            }
        }
        private Nullable<global::System.Decimal> _RentalPerDay;
        partial void OnRentalPerDayChanging(Nullable<global::System.Decimal> value);
        partial void OnRentalPerDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Available
        {
            get
            {
                return _Available;
            }
            set
            {
                OnAvailableChanging(value);
                ReportPropertyChanging("Available");
                _Available = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Available");
                OnAvailableChanged();
            }
        }
        private Nullable<global::System.Boolean> _Available;
        partial void OnAvailableChanging(Nullable<global::System.Boolean> value);
        partial void OnAvailableChanged();

        #endregion

    
    }

    #endregion

    
}
